export const STORES = [
  {
    id: "store-a",
    name: "Store A",
    address: "112 Birchwood Ave, Mellow",
    distance: "0.3 mi",
    healthScore: 92,
    basketCost: "$28.40",
    affordable: ["Bananas", "Oats", "Canned Beans", "Spinach", "Eggs"],
    lat: 40.7128,
    lng: -74.006,
  },
  {
    id: "store-b",
    name: "Store B",
    address: "347 Elmridge Blvd, Mellow",
    distance: "0.7 mi",
    healthScore: 78,
    basketCost: "$24.15",
    affordable: ["Apples", "Brown Rice", "Lentils", "Carrots", "Greek Yogurt"],
    lat: 40.7148,
    lng: -74.009,
  },
  {
    id: "store-c",
    name: "Store C",
    address: "589 Maplewood Dr, Mellow",
    distance: "1.1 mi",
    healthScore: 85,
    basketCost: "$31.60",
    affordable: ["Sweet Potatoes", "Canned Tuna", "Peanut Butter", "Broccoli", "Whole Wheat Bread"],
    lat: 40.7108,
    lng: -74.003,
  },
  {
    id: "store-d",
    name: "Store D",
    address: "204 Cedarstone Rd, Mellow",
    distance: "1.5 mi",
    healthScore: 70,
    basketCost: "$21.90",
    affordable: ["Cabbage", "Dried Lentils", "Canned Tomatoes", "Onions", "Frozen Peas"],
    lat: 40.7168,
    lng: -74.012,
  },
  {
    id: "store-e",
    name: "Store E",
    address: "813 Pinehurst Lane, Mellow",
    distance: "2.0 mi",
    healthScore: 88,
    basketCost: "$35.20",
    affordable: ["Kale", "Quinoa", "Chickpeas", "Avocados", "Almond Milk"],
    lat: 40.7088,
    lng: -73.999,
  },
];

export const MEAL_PLAN = [
  {
    day: "Mon",
    breakfast: { name: "Oatmeal + Banana", cal: 380 },
    lunch: { name: "Lentil Soup + Bread", cal: 490 },
    dinner: { name: "Bean Rice Bowl", cal: 560 },
    cost: "$4.20",
  },
  {
    day: "Tue",
    breakfast: { name: "Eggs + Toast", cal: 340 },
    lunch: { name: "Tuna Salad Wrap", cal: 450 },
    dinner: { name: "Veggie Stir-Fry", cal: 520 },
    cost: "$5.10",
  },
  {
    day: "Wed",
    breakfast: { name: "Greek Yogurt + Apple", cal: 290 },
    lunch: { name: "Peanut Butter Sandwich", cal: 480 },
    dinner: { name: "Sweet Potato + Beans", cal: 540 },
    cost: "$3.90",
  },
  {
    day: "Thu",
    breakfast: { name: "Oatmeal + Berries", cal: 360 },
    lunch: { name: "Chickpea Salad", cal: 410 },
    dinner: { name: "Brown Rice + Spinach", cal: 480 },
    cost: "$4.50",
  },
  {
    day: "Fri",
    breakfast: { name: "Banana + Peanut Butter", cal: 400 },
    lunch: { name: "Veggie Soup", cal: 320 },
    dinner: { name: "Pasta + Canned Tomatoes", cal: 590 },
    cost: "$4.80",
  },
  {
    day: "Sat",
    breakfast: { name: "Eggs + Vegetables", cal: 370 },
    lunch: { name: "Quinoa Bowl", cal: 460 },
    dinner: { name: "Lentil Curry + Rice", cal: 610 },
    cost: "$5.60",
  },
  {
    day: "Sun",
    breakfast: { name: "Oatmeal + Walnuts", cal: 420 },
    lunch: { name: "Bean Burrito", cal: 530 },
    dinner: { name: "Baked Potato + Salad", cal: 470 },
    cost: "$4.10",
  },
];

export const BUDGET = {
  monthly: 280,
  spent: 163,
  remaining: 117,
  avgSavings: 47,
  weeklySpend: [38, 42, 35, 48],
};
